#Fasta file reader. Can separate components of fasta file and display them to the user for easier reading.

file = ">KT995182.1 Brachymystax lenok CDGSH iron sulfur domain 2 (cisd2) mRNA, partial cds TCCAGCCTACCTCAAGAAGTTCCCCCTTCCCGAGACGATCGGAGGATTTGCGAGGTTAACAGTCTCTGAGTGGCTCCGGTTGCTGCCTCTCCTGGGAATCCTGGCCCTGCTGGGCTACCTCACCATCCGGCCCTTCCTGCCCAAGAAGAAGAAGCAGAAGGACAGCCTGATCAACCTGAAGATCCAGAAAGAGAACCCCAAAGTGGTCAACGAGATCGATATTGAGGACTTGAAGAGAACAAACGTCTGCTACTGCCGCTGCTGGCGCTCCAAAACGTTTCCTGTTTGTGACAAATCACACATAAAGCACAAC>XM_037317523.1 Colletotrichum aenigma Thioredoxin reductase sirT (sirT), partial mRNAATGGCCTCAGACTCGACAATGACACCACACGTCCTCAGAAACGTTCTCGATGTCTGCATCATTGGGGCCGGTCCCGCGGGTCTATCTGCGGCCCTATCTCTCGGTAGGGTTCTTCGAAGCGCCGTAGTGTTTGACTCGGGAGACTGGAAGGCGCACAACGTCTCTCGTATCGGCGGAGCTCACGACCAGGATAGTCCATCTTTGATTCGAAATGGGCTGAAGGCAGAGCTGCAACGAAAGTACAAGACCATCATGTTTGCCAAGACAGCGGCCAGAACTATTCGTGAGGCCGATCCCGTCTTCGAGGTAGAAGATGAGAACGGACGGTGTTGGAAAAGTAGAAAGGTGATTTTGGCGACAGGCACTCGTGATGTGCTGCCAGATATCGCGGGATACAAAGAATGTTGGGGGAATGGAATATTCAACTGCATGCACCGTTCAGGATTTGAAAAGTTCGGTGCCGTCAACGCAGCTGTTCTTCTCACTTCAACCAGTAGTATCAAGCTTTCCGACGCGATCTCGTGCGGTCAACTTGCACGGCAATTTTCGACAAACATATGCCTGTTGACCAATGGTACCGGATCCTTGACCCTTGGCGATGTACACAAAGCAGCCGAAATCCACAGTCTAAAAGTGGACGACCGAAAGATTCGGAGACTCCATACTTTGGGCTACAATAGCGATGCTTCAATGGTTGTCAAGTTTGAGGATGGAACAACGTCGTCGTTTGGCTTCCTCTTCCACAAGGCTGACACAGTTCCCAACGGGGGTTTCGCAGAGCAACTTGGTTTGGAAACTACGCAAACTGGAGATGTCTCGATTTCGGGCTATATGCAAGAGACAACCAGAAGAGGCGTGTTTGCGGCTGGCGACTGTGCCACACAGGTGAAGCAGGTGTCTGTCGCTATGGGTGCTGGTTCCGCTGCTGGAGTTGGAGCAAACGCGCAGATACTGAAGGATGACTTCGAGAAAGATTGGTGA"

c = file.count(">")
e = c+1
f = ""

if c > 1:
	f= file.split(">")

for i in range(1, e):
	f11 = f[i]
	
	f1 = f11.split()
	A = f1[0]
	Acc_no = A[1:]
	blank = " "
	Org_name = f1[1] + blank + f1[2]
	D = f1[3:-1]
	Detail = ' '.join(map(str, D))
	Seq =f1[-1]

	print("Accession Number:", Acc_no, "\nOrganism Name:", Org_name, "\nDetails:", Detail, "\nSequence:", Seq, "\n")

"""
if c > 1:
	f = file.split(">")

f1 = f.split()
A = f1[0]
Acc_no = A[1:]
blank = " "
Org_name = f1[1] + blank + f1[2]
D = f1[3:-1]
Detail = ' '.join(map(str, D))
Seq =f1[-1]

print("Accession Number:", Acc_no, "\nOrganism Name:", Org_name, "\nDetails:", Detail, "\nSequence:", Seq)
"""


	